version: "3"
services:
  afxdotnetcoresample:
    restart: always
    privileged: true
    image: afxdotnetcoresample:v1.0.0.2
    ports:
       - "80:80"
    volumes:
       - "/logs/afx:/app/logs"
    environment:
      - AfxDotNetCoreSample:ServerUrls=http://*:80  
        