version: "3"
networks:
  afx:
    external:
      name: afx
services:
  afx:
    image: 192.168.1.8/afx:v1.0.0.2
    ports:
       - "80:80"
    volumes:
       - "/logs/afx:/app/logs"
    environment:
      - AfxDotNetCoreSample:ServerUrls=http://*:80
    deploy:
      replicas: 3
    networks:
      - afx