version: "3"
services:
  afxdotnetcoresample:
    image: afxdotnetcoresample:v1.0.0.1
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
       - "80:80"
    volumes:
       - "/home/logs/AfxDotNetCoreSample:/app/log"
    environment:
      - AfxDotNetCoreSample:ServerUrls=http://*:80  
    privileged: true
    restart: always